sudo: true
language: objective-c

env:
    global:
    - USERNAME="kentzzhang"
    - REPONAME="swift-CI-Test"

before_script:
    # - brew update && brew upgrade xctool
    # - gem install cocoapods
    - sudo pip install requests[security] jira

script:
    # - sh test.sh
    # - xctool -workspace SwiftTravis.xcworkspace -scheme SwiftTravis -sdk iphonesimulator clean build test
    - echo "script exec"


after_script:
    - python ci.py -u=$USERNAME -r=$REPONAME -c=$TRAVIS_COMMIT

branches:
  only:
    - master
