sudo: true
language: objective-c

env:
    global:
    - USERNAME="kentzzhang"
    - REPONAME="swift-CI-Test"

before_script:
    # - brew update && brew upgrade xctool
    # - gem install cocoapods
    - echo $TRAVIS_COMMIT
    - sudo pip install requests jira
    # set the status of the JIRA story => building
    # for example, change status to IN Progress
    #- python ci.py $USERNAME $REPONAME $TRAVIS_COMMIT

script:
    # - sh test.sh
    # - xctool -workspace SwiftTravis.xcworkspace -scheme SwiftTravis -sdk iphonesimulator clean build test
    - echo "script exec"


after_script:
    # 
    - python ci.py -u=$USERNAME -r=$REPONAME -c=$TRAVIS_COMMIT
    # change status to ToDo

branches:
  only:
    - master
