language: objective-c


before_script:
    - brew update && brew upgrade xctool

script:
    - xctool -workspace SwiftTravis.xcworkspace -scheme SwiftTravis -sdk iphonesimulator clean build test

branches:
  only:
    - master
